kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: primary-pvc
  namespace: primary  
  annotations:
    trident.netapp.io/shareToNamespace: secondary
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: fsx-basic-block-ontap-nas